-- spring data JDBC does not auto create tables

CREATE TABLE IF NOT EXISTS "users" (
    "ID" BIGINT AUTO_INCREMENT PRIMARY KEY,
    "LOGIN" varchar(255) NOT NULl UNIQUE,
    "FIRSTNAME" VARCHAR(255) NOT NULL,
    "LASTNAME" VARCHAR(255) NOT NULL,
    "DESCRIPTION" TEXT
);

CREATE TABLE IF NOT EXISTS "article" (
    "ID" BIGINT AUTO_INCREMENT PRIMARY KEY,
    "TITLE" VARCHAR(255) NOT NULL,
    "HEADLINE" VARCHAR(500) NOT NULL,
    "CONTENT" TEXT NOT NULL,
    "author_id" BIGINT NOT NULL,
    "SLUG" VARCHAR(255) NOT NULL UNIQUE,
    "ADDED_AT" TIMESTAMP NOT NULL,
    FOREIGN KEY ("author_id") REFERENCES "users"("ID")
);